name: 'localbike_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuration des modèles
models:
  localbike_project:    
    +materialized: view  
    +persist_docs:
      relation: true
      columns: true
    
    # Si vous voulez des configurations spécifiques pour le dossier stg
    stg:
      +materialized: view
      +persist_docs:
        relation: true
        columns: true