version: 2

models:
  - name: report_monthly_sales
    description: "Rapport mensuel des ventes pour analyse des tendances"
    columns:
      - name: month
        description: "Mois de l'analyse"
        tests:
          - unique
          - not_null

  - name: report_category_performance
    description: "Performance des ventes par catégorie"
    columns:
      - name: category_name
        description: "Nom de la catégorie"
        tests:
          - unique
          - not_null

  - name: report_store_performance
    description: "KPIs de performance par magasin"
    columns:
      - name: store_name
        description: "Nom du magasin"
        tests:
          - unique
          - not_null
      - name: state
        description: "État du magasin"

  - name: report_customer_segments
    description: "Analyse des segments clients"
    columns:
      - name: customer_segment
        description: "Segment client (High/Medium/Low Value)"
        tests:
          - unique
          - not_null
      - name: number_of_customers
        description: "Nombre de clients dans le segment"
      - name: avg_revenue_per_customer
        description: "Revenu moyen par client"
      - name: total_segment_revenue
        description: "Revenu total du segment"

  - name: report_top_products
    description: "Classement des produits par performance"
    columns:
      - name: product_name
        description: "Nom du produit"
      - name: category_name
        description: "Catégorie du produit"
      - name: units_sold
        description: "Unités vendues"
      - name: revenue
        description: "Revenu total"
      - name: avg_unit_price
        description: "Prix unitaire moyen"
      - name: current_stock
        description: "Stock actuel"